// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function H1(Props) {
  var title = Props.title;
  var className = Props.className;
  var className$1 = className !== undefined ? className : "text-4xl font-semibold text-center";
  return React.createElement("h1", {
              className: className$1
            }, title);
}

var make = H1;

export {
  make ,
  
}
/* react Not a pure module */
