// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as FetchCountries from "../helpers/FetchCountries.mjs";

function make(param) {
  var match = React.useState(function () {
        return [];
      });
  var setCountries = match[1];
  React.useEffect((function () {
          var __x = FetchCountries.getAll(undefined);
          __x.then(function (res) {
                Curry._1(setCountries, (function (param) {
                        return res;
                      }));
                return Promise.resolve(undefined);
              });
          
        }), []);
  return match[0];
}

export {
  make ,
  
}
/* react Not a pure module */
