// Generated by ReScript, PLEASE EDIT WITH CARE


var apiUrl = "https://restcountries.com/v3.1/";

function getAll(param) {
  var endpointApi = "https://restcountries.com/v3.1/all";
  var __x = fetch(endpointApi);
  var __x$1 = __x.then(function (prim) {
        return prim.json();
      });
  return __x$1.then(function (json) {
              return Promise.resolve((console.log(json), undefined));
            });
}

export {
  apiUrl ,
  getAll ,
  
}
/* No side effect */
