// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function P(Props) {
  var className = Props.className;
  var children = Props.children;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("p", tmp, children);
}

var make = P;

export {
  make ,
  
}
/* react Not a pure module */
