// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function P(Props) {
  var className = Props.className;
  var children = Props.children;
  return React.createElement("p", {
              className: className
            }, children);
}

var make = P;

export {
  make ,
  
}
/* react Not a pure module */
