// Generated by ReScript, PLEASE EDIT WITH CARE


function nameToJs(param) {
  return {
          common: param.common,
          official: param.official
        };
}

function nameFromJs(param) {
  return {
          common: param.common,
          official: param.official
        };
}

function flagImgToJs(param) {
  return {
          png: param.png,
          svg: param.svg
        };
}

function flagImgFromJs(param) {
  return {
          png: param.png,
          svg: param.svg
        };
}

function mapsToJs(param) {
  return {
          googleMaps: param.googleMaps,
          openStreetMaps: param.openStreetMaps
        };
}

function mapsFromJs(param) {
  return {
          googleMaps: param.googleMaps,
          openStreetMaps: param.openStreetMaps
        };
}

function countryToJs(param) {
  return {
          name: param.name,
          independant: param.independant,
          unMember: param.unMember,
          capital: param.capital,
          region: param.region,
          subregion: param.subregion,
          flag: param.flag,
          flags: param.flags,
          maps: param.maps,
          population: param.population
        };
}

function countryFromJs(param) {
  return {
          name: param.name,
          independant: param.independant,
          unMember: param.unMember,
          capital: param.capital,
          region: param.region,
          subregion: param.subregion,
          flag: param.flag,
          flags: param.flags,
          maps: param.maps,
          population: param.population
        };
}

export {
  nameToJs ,
  nameFromJs ,
  flagImgToJs ,
  flagImgFromJs ,
  mapsToJs ,
  mapsFromJs ,
  countryToJs ,
  countryFromJs ,
  
}
/* No side effect */
