// Generated by ReScript, PLEASE EDIT WITH CARE

import * as P from "./components/P/P.mjs";
import * as React from "react";

function $$default(param) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "text-3xl font-semibold"
                }, "What is this about?"), React.createElement(P.make, {
                  className: "mb-2",
                  children: "Coucou"
                }));
}

export {
  $$default ,
  $$default as default,
  
}
/* P Not a pure module */
