// Generated by ReScript, PLEASE EDIT WITH CARE

import * as H1 from "./components/H1/H1.mjs";
import * as React from "react";

function $$default(param) {
  return React.createElement(React.Fragment, undefined, React.createElement(H1.make, {
                  title: "Countries"
                }));
}

export {
  $$default ,
  $$default as default,
  
}
/* H1 Not a pure module */
